<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Order_product_model extends CI_Model
{

    public $table = 'order_product';
    public $id = 'order_product_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('order_product_id', $q);
	$this->db->or_like('orderId', $q);
	$this->db->or_like('productId', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('base_svg', $q);
	$this->db->or_like('sizes', $q);
	$this->db->or_like('quantities', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('middle_svg', $q);
	$this->db->or_like('top_svg', $q);
	$this->db->or_like('model_obj', $q);
	$this->db->or_like('model_mtl', $q);
	$this->db->or_like('generate_file_name', $q);
	$this->db->or_like('session_user', $q);
	$this->db->or_like('imgoffsety', $q);
	$this->db->or_like('imgoffsetx', $q);
	$this->db->or_like('imgangle', $q);
	$this->db->or_like('myRange', $q);
	$this->db->or_like('imgrepeat', $q);
	$this->db->or_like('patterenused', $q);
	$this->db->or_like('tax', $q);
	$this->db->or_like('reward', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('order_product_id', $q);
	$this->db->or_like('orderId', $q);
	$this->db->or_like('productId', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('base_svg', $q);
	$this->db->or_like('sizes', $q);
	$this->db->or_like('quantities', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('total', $q);
	$this->db->or_like('middle_svg', $q);
	$this->db->or_like('top_svg', $q);
	$this->db->or_like('model_obj', $q);
	$this->db->or_like('model_mtl', $q);
	$this->db->or_like('generate_file_name', $q);
	$this->db->or_like('session_user', $q);
	$this->db->or_like('imgoffsety', $q);
	$this->db->or_like('imgoffsetx', $q);
	$this->db->or_like('imgangle', $q);
	$this->db->or_like('myRange', $q);
	$this->db->or_like('imgrepeat', $q);
	$this->db->or_like('patterenused', $q);
	$this->db->or_like('tax', $q);
	$this->db->or_like('reward', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Order_product_model.php */
/* Location: ./application/models/Order_product_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-11 09:05:39 */
/* http://harviacode.com */